{% set version = "0.4.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-easyverification
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/easyVerification_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/easyVerification/easyVerification_{{ version }}.tar.gz
  sha256: 6c46715bbf87bd46aec22556222b641ffd43cea8a13e819c3ce00166a16bc2cc

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.12.9
    - r-specsverification >=0.5
    - r-pbapply
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.9
    - r-specsverification >=0.5
    - r-pbapply

test:
  commands:
    - $R -e "library('easyVerification')"           # [not win]
    - "\"%R%\" -e \"library('easyVerification')\""  # [win]

about:
  home: http://www.meteoswiss.ch
  summary: Set of tools to simplify application of atomic forecast verification metrics for (comparative) verification of ensemble forecasts to large data sets. The forecast metrics are imported from the 'SpecsVerification' package, and additional forecast metrics are provided with this package. Alternatively, new user-defined
    forecast scores can be implemented using the example scores provided and applied using the functionality of this package.
  license: GPL-3.0-only
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa
